### ISSUE TITLE
feature: withAny tool argument

### ISSUE THREAD

**Issue by 0xNF** [mark3labs/mcp-go#345]
## Problem Statement

There's no way to specify that a tool argument can be any shape. withNumber, withBoolean, withArray, withObject, withString exist, but there's nothing for a schema-less type. 

## Proposed Solution

JSON Schema defines the any type as an empty object:
```
"properties": {
        "F1": {
            "type": "string"
        },
        "F2": {
            "type": "integer"
        },
        "F3": {}
    },
```
where F3 is any. 

I'd like to see a withAny tool argument method.

## Example Usage

```go

	tool := mcp.NewTool(
		toolName,
		mcp.WithDescription(toolDescription),
		mcp.WithAny("freeEntry"),
	)
```

**Comment by pottekkat** [comment]
Thank for opening this issue. This seems like a valid request. You can currently use the workaround with `NewToolWithRawSchema()` but this means you have to define the whole schema manually. But the `WithAny` helper function can be added.

**Comment by 1garo** [comment]
@pottekkat  I would like to contribute, could I start from this one?

**Comment by pottekkat** [comment]
Thank you @1garo. Feel free to open a pull request.

**Comment by 1garo** [comment]
@0xNF could you please give us an example on how you would use it? It would also be useful when adding it to the examples. I couldn't think one.

**Comment by 0xNF** [comment]
I can just paste some of the actual OpenAPI spec I'm working with:

```yaml
RunRequest:
      required:
      - id
      type: object
      properties:
        id:
          type: string
          description: Id of the item to execute
        in:
          description: Initial input to the execution
          nullable: true
        extra:
          type: object
          additionalProperties: {}
          description: json map of extra metadata
```

As you can see, the `in` can be any format. It's a primitive, a list of primitives, an object of primitives, a list of complex types, an object of complex types, nulls, not nulls, etc. It's a freeform field. Representing this in the current sdk is difficult.
